version: "3"
services:
  authors:
    image: supra89kren/bff-authors-service:1.0
    container_name: bff-authors-service
    ports:
      - 8081:8081
    networks:
      - mynet
  books:
    image: supra89kren/bff-books-service:1.0
    container_name: bff-books-service
    ports:
      - 8082:8082
    networks:
      - mynet
  web-sockets:
    image: supra89kren/bff-web-sockets-service:1.0
    container_name: bff-web-sockets-service
    ports:
      - 8083:8083
    networks:
      - mynet
  redis:
    image: redis:latest
    container_name: bff-redis
    ports:
      - 16379:6379
    networks:
      - mynet

  bff-frontend:
    image: supra89kren/bff-frontend:1.0
    container_name: bff-frontend-service
    ports:
       - 8084:8084
    networks:
        - mynet

  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql
    networks:
      - mynet

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
    depends_on:
      - storage
    networks:
      - mynet
networks:
  mynet:
